### ISSUE TITLE
Feature request: Loading spinner

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/nori#46]
Not important nor urgent, but it might be nice to have a loading spinner when there's no other indication that it hasn't crashed. E.g. https://github.com/sindresorhus/ora

**Comment by quarterto** [comment]
since this issue, i've written a nice concurrent spinners library for löb which i plan to extract as a module. benefits over other libraries:

### vs [ora](https://github.com/sindresorhus/ora)

- supports multiple spinners
- more opinionated, aimed towards concurrent operations

### vs [node-multispinner](https://github.com/codekirei/node-multispinner)

- simpler/more flexible API
- supports adding spinners while others are in progress
